CREATE TABLE menu_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL,
  price DOUBLE(10,2) NOT NULL,
  store_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE stores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  email TEXT NULL,
  phone_number TEXT NULL,
  logo_url TEXT NOT NULL,
  location TEXT NOT NULL,
  longitude DOUBLE(10,6) NOT NULL,
  latitude DOUBLE(10,6) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  service TEXT NOT NULL,
  customer_name TEXT NULL,
  customer_mobile TEXT NULL,
  customer_address TEXT NULL,
  customer_unit_number TEXT NULL,
  customer_instructions TEXT NULL,
  lat_coordinates DOUBLE(10,6) NULL,
  lng_coordinates DOUBLE(10,6) NULL,
  payment_method TEXT NULL,
  subtotal DOUBLE(10,2) NULL,
  delivery_fee DOUBLE(10,2) NULL,
  total DOUBLE(10,2) NULL,
  status VARCHAR(255) NULL DEFAULT 'pending',
  order_date TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  shipday_order_id INT NULL,
  shipday_data JSONB NULL
);

CREATE TABLE order_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  name TEXT NULL,
  price DOUBLE(10,2) NULL,
  quantity INT NULL,
  store_id INT NULL,
  store_name TEXT NULL,
  store_logo TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE menu_photos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  photo_url TEXT NOT NULL,
  store_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE fare_rates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  base_fare DOUBLE(10,2) NOT NULL,
  rate_per_km DOUBLE(10,2) NOT NULL,
  other_charges DOUBLE(10,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO fare_rates (base_fare, rate_per_km, other_charges) VALUES (40, 10, 0);